server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /api/wakapi/all-time {
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host wakatime.lth.so;
    proxy_set_header Connection "";
    proxy_pass https://wakatime.lth.so/api/compat/wakatime/v1/users/current/all_time_since_today?api_key=47ba4fcc-ed5c-404e-8c14-4a0beb6c16fd;
  }

  location = /api/spotify/top/songs {
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host spotify.lth.so;
    proxy_set_header Connection "";
    proxy_pass https://spotify.lth.so/api/spotify/top/songs;
  }

  location = /api/ghost {
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host blog.lth.so;
    proxy_set_header Connection "";
    proxy_pass https://blog.lth.so/ghost/api/content/posts/?key=86693ef2e9d42b6948a4bc2446&limit=1;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
