server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /api/wakapi/all-time {
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host wakatime.lth.so;
    proxy_set_header Connection "";
    proxy_pass https://wakatime.lth.so/api/compat/wakatime/v1/users/current/all_time_since_today?api_key=cc688ee2-cdb1-4599-8e17-ae7f0dd2bae1;
  }

  location = /api/spotify/top/songs {
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host spotify.lth.so;
    proxy_set_header Connection "";
    proxy_pass https://spotify.lth.so/api/spotify/top/songs;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
